### ISSUE TITLE
Update for Zotero 7

### ISSUE THREAD

**Issue by SR--** [dcartertod/zotero-plugins#26] opened 2023-05-25 07:48 UTC
Keen to see this, please.

**Comment by dcartertod** [comment] 2023-05-26 01:54
I have not looked at this yet. Will do.

**Comment by tendernesses** [comment] 2023-08-11 05:58
looking forward to the update

**Comment by dcartertod** [comment] 2023-08-11 12:47
I do intend to. Working on my Chapter 4 at the moment! ;-)

**Comment by omundy** [comment] 2023-09-02 13:35
![image](https://github.com/dcartertod/zotero-plugins/assets/279945/67b3582b-5503-4a21-867d-113a1012f128)

🙏 bump

**Comment by odysseus90210** [comment] 2023-12-14 19:53
Am also eagerly awaiting an update for Zotero 7, please!

**Comment by join-xu2021** [comment] 2023-12-28 13:05
Looking forward to applying this plugin to zotero7, so needed!

**Comment by WMAM** [comment] 2024-01-08 16:56
> Am also eagerly awaiting an update for Zotero 7, please! But if I may make a suggestion, don't label the preview tab "Preview" because there's already another add-on that previews pdf attachments in a "Preview" pane.

Chronologically this add-on was created before the PDF viewer. For that reason, the PDF viewer allows you to configure the tab name.
Hopefully we can have this add-on adapted for Z-7 soon. Thank you!

**Comment by odysseus90210** [comment] 2024-01-08 17:18
Great. Thanks!

**Comment by jeron1** [comment] 2024-01-31 00:48
Looking forward too. Use this plugin all the time. I probably clicked on the Preview tab (on Z-6) about 35 times last night.

**Comment by dcartertod** [comment] 2024-02-23 13:36
Just a heads-up that I have started working on this.

**Comment by dcartertod** [comment] 2024-02-25 22:10
I have just released the Zotero 7 version of the plugin. It's pretty solid, I think.

**Comment by SR--** [comment] 2024-02-25 22:28
Thank you, much grateful. Not using the beta but shall look forward to it in 7.

**Comment by omundy** [comment] 2024-02-26 19:20
@dcartertod thank you! I had to restart to install the updated version and just saw the Zotero reskin (now in `7.0.0-beta.62+b15fb36f1`). 

1. I Iove that I can see the preview update as I add data to the citation.
2. Is it possible to move the preview under a heading (which can be collapsed/expanded) to match the new sidebar category style?
3. Could I choose which version (the whitespaced vs. not) I prefer to see? They hold the same data, and I usually just Cmd+Shift+V to match the style and dump the formatting when I copy.
4. Speaking of copying, clicking the copy icons (emoji) doesn't work. 
5. IDK if Zotero is using an open source icon set that has the "double overlapping document" copy icon, but if not I would be happy to create one to match the new interface? LMK!

![image](https://github.com/dcartertod/zotero-plugins/assets/279945/1692c33b-fea2-4306-b099-aabb23a491f8)

**Comment by dcartertod** [comment] 2024-02-26 19:27
1. I Iove that I can see the preview update as I add data to the citation.

Thanks

2. Is it possible to move the preview under a heading (which can be collapsed/expanded) to match the new sidebar category style?

I'll have to look into that. I'm sure it is.

3. Could I choose which version (the whitespaced vs. not) I prefer to see? They hold the same data, and I usually just Cmd+Shift+V to match the style and dump the formatting when I copy.

What citation style are you using? In mine (APA 7) you get the Bibliography and the In Text, which are substantially different, but yes, I can probably do that.

4. Speaking of copying, clicking the copy icons (emoji) doesn't work.

Oh. They were in my testing on Windows. What OS?

7. IDK if Zotero is using an open source icon set that has the "double overlapping document" copy icon, but if not I would be happy to create one to match the new interface? LMK!

I'm actually using Unicode with CSS positioning. I don't believe that they are using an icon set (to my knowledge), but I've not looked into it.

**Comment by omundy** [comment] 2024-02-26 19:41
3. Chicago. It's showing the same text.
4. Mac (13.6)
5. The icons under the headings. It looks like there is a "duplicate.svg" right here https://github.com/zotero/zotero/blob/5dcaf6575799db11b910b102733ad7d24e46f2c7/chrome/skin/default/zotero/16/universal/duplicate.svg 

```svg
<svg width="16" height="16" viewBox="0 0 16 16" fill="black" xmlns="http://www.w3.org/2000/svg">
<path d="M12 3V0H1V13H4V16H15V3H12ZM2 1H11V12H2V1ZM14 15H5V13H12V4H14V15Z" fill="context-fill"/>
</svg>
```

![image](https://github.com/dcartertod/zotero-plugins/assets/279945/9fdfed3e-33b8-4293-a33a-4738e5adb99f)

**Comment by dcartertod** [comment] 2024-02-27 02:48
I've added the SVG, and now have a number of display options in the settings, including only having the bibliography, as well as line height and font size.

I have not yet addressed the collapsible element thing, nor the copy problem (which I cannot currently reproduce).

I have opened separate issues for those: #29, #28, so I'm closing this one. Please comment in those or open a new issue if you run into something.

Thank you for your patience (I defend my dissertation in just over a week from now!)

**Closed by dcartertod** 2024-02-27 02:48 UTC

**Comment by omundy** [comment] 2024-02-27 18:44
@dcartertod you bet. Good luck!

**Comment by 7596ff** [comment] 2024-04-11 01:24
Hi, I hope the defense went well; I hate to bother but is the Abstract Cleaner also coming?
